#
# Created by olehka on 02.08.2020.
#

name: Android Master CI

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Assemble-Upload Debug Apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Assemble debug APK
          run: ./gradlew assembleDebug --stacktrace
      - name: Upload debug APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/**/debug/*.apk