#
# Created by olehka on 02.08.2020.
#

name: Android Master CI

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Assemble-Upload Debug Apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Decode google-services.json (1)
        env:
          GOOGLE_SERVICES_SECRET: ${{ secrets.GOOGLE_SERVICES_SECRET }}
        run: echo $GOOGLE_SERVICES_SECRET > app/src/korolishut/google-services.json; echo $GOOGLE_SERVICES_SECRET > app/src/tsoikinoband/google-services.json
      - name: Decode google-services.json (2)
        env:
          GOOGLE_SERVICES_SECRET_2: ${{ secrets.GOOGLE_SERVICES_SECRET_2 }}
        run: echo $GOOGLE_SERVICES_SECRET_2 > app/src/kuzmaskryabin/google-services.json; echo $GOOGLE_SERVICES_SECRET_2 > app/src/sektorgaza/google-services.json
      - name: Assemble debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload debug APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/**/debug/*.apk