#
# Created by olehka on 02.08.2020.
#

name: Android Feature CI

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: bash ./gradlew build --stacktrace